kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:

## Run the fips (debug) unittest endpoint
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

## Run the release inittest endpoint
- name: build-fips-release
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-release-unittest
    - ./fips build

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
